package es.uva.bluemanzana.interfaz.paresvistacontrol;

import es.uva.bluemanzana.interfaz.paresvistacontrol.IdentificarseVistaCtrl;
import es.uva.bluemanzana.negocio.modelo.Usuario;
import javax.swing.JOptionPane;

/**
 * Clase que implementa la interfaz cuando el usuario realiza el caso de uso de
 * Identificarse,
 *
 * @author sergsan
 * @author juatorr
 * @author pabvare
 */
public class IdentificarseVista extends javax.swing.JFrame {

    private IdentificarseVistaCtrl controlador;
    private Usuario usuario = null;

    /**
     * Constructor de la interfaz.
     *
     * @param user
     */
    public IdentificarseVista(Usuario user) {
        initComponents();
        usuario = user;
        solicitarVacacionesBtn.setEnabled(true);
        registrarNuevoEmpleadoBtn.setEnabled(false);
        erteBtn.setEnabled(false);
        recepcionPedidoTiendaBtn.setEnabled(false);
        realizarPedidoBtn.setEnabled(false);
        disponibilidadProductoBtn.setEnabled(false);
        enviarProductoAlmacenBtn.setEnabled(false);
        controlador = new IdentificarseVistaCtrl(usuario, this);
        if (usuario == null) {
            usuario = new Usuario();
            opcionesPanel.setVisible(false);
        } else {
            iniciarSesionPanel.setVisible(false);
            controlador.procesarRol(usuario);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iniciarSesionPanel = new javax.swing.JPanel();
        empresaLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        nombreUsuarioTextField = new javax.swing.JTextField();
        contrasenaField = new javax.swing.JPasswordField();
        iniciarSesionBtn = new javax.swing.JToggleButton();
        contrasenaLabel = new javax.swing.JLabel();
        opcionesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        solicitarVacacionesBtn = new javax.swing.JButton();
        registrarNuevoEmpleadoBtn = new javax.swing.JButton();
        erteBtn = new javax.swing.JButton();
        recepcionPedidoTiendaBtn = new javax.swing.JButton();
        realizarPedidoBtn = new javax.swing.JButton();
        disponibilidadProductoBtn = new javax.swing.JButton();
        enviarProductoAlmacenBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        empresaLabel.setText("Blue Manzana");

        dniLabel.setText("DNI: ");

        iniciarSesionBtn.setText("Iniciar Sesión");
        iniciarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionBtnActionPerformed(evt);
            }
        });

        contrasenaLabel.setText("Contraseña: ");

        javax.swing.GroupLayout iniciarSesionPanelLayout = new javax.swing.GroupLayout(iniciarSesionPanel);
        iniciarSesionPanel.setLayout(iniciarSesionPanelLayout);
        iniciarSesionPanelLayout.setHorizontalGroup(
            iniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iniciarSesionPanelLayout.createSequentialGroup()
                .addGap(0, 156, Short.MAX_VALUE)
                .addComponent(iniciarSesionBtn)
                .addGap(149, 149, 149))
            .addGroup(iniciarSesionPanelLayout.createSequentialGroup()
                .addGroup(iniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(iniciarSesionPanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(empresaLabel))
                    .addGroup(iniciarSesionPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(iniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dniLabel)
                            .addComponent(contrasenaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(iniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contrasenaField, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(nombreUsuarioTextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        iniciarSesionPanelLayout.setVerticalGroup(
            iniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iniciarSesionPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(empresaLabel)
                .addGap(26, 26, 26)
                .addGroup(iniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniLabel)
                    .addComponent(nombreUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(iniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrasenaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contrasenaLabel))
                .addGap(38, 38, 38)
                .addComponent(iniciarSesionBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Opciones Perfil");

        solicitarVacacionesBtn.setText("Solicitar vacaciones");
        solicitarVacacionesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                solicitarVacacionesBtnMouseClicked(evt);
            }
        });

        registrarNuevoEmpleadoBtn.setText("Registrar nuevo empleado");
        registrarNuevoEmpleadoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarNuevoEmpleadoBtnMouseClicked(evt);
            }
        });

        erteBtn.setText("Sacar empleado de ERTE");
        erteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                erteBtnMouseClicked(evt);
            }
        });

        recepcionPedidoTiendaBtn.setText("Recepcion de producto en tienda fisica");
        recepcionPedidoTiendaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recepcionPedidoTiendaBtnMouseClicked(evt);
            }
        });

        realizarPedidoBtn.setText("Realizar pedido de suministro");
        realizarPedidoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                realizarPedidoBtnMouseClicked(evt);
            }
        });

        disponibilidadProductoBtn.setText("Consultar disponibilidad de producto ");
        disponibilidadProductoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disponibilidadProductoBtnMouseClicked(evt);
            }
        });

        enviarProductoAlmacenBtn.setText("Enviar productos a almacen");
        enviarProductoAlmacenBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarProductoAlmacenBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout opcionesPanelLayout = new javax.swing.GroupLayout(opcionesPanel);
        opcionesPanel.setLayout(opcionesPanelLayout);
        opcionesPanelLayout.setHorizontalGroup(
            opcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesPanelLayout.createSequentialGroup()
                .addGroup(opcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opcionesPanelLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1))
                    .addGroup(opcionesPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(solicitarVacacionesBtn))
                    .addGroup(opcionesPanelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(opcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(erteBtn)
                            .addComponent(registrarNuevoEmpleadoBtn)))
                    .addGroup(opcionesPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(realizarPedidoBtn))
                    .addGroup(opcionesPanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(opcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(disponibilidadProductoBtn)
                            .addComponent(recepcionPedidoTiendaBtn)))
                    .addGroup(opcionesPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(enviarProductoAlmacenBtn)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        opcionesPanelLayout.setVerticalGroup(
            opcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(solicitarVacacionesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarNuevoEmpleadoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recepcionPedidoTiendaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(realizarPedidoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disponibilidadProductoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviarProductoAlmacenBtn)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciarSesionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(opcionesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iniciarSesionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 254, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(opcionesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(89, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Controlador de eventos del boton iniciarSesion
     *
     * @param evt
     */
    private void iniciarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionBtnActionPerformed
        controlador.procesarInicioSesion();
    }//GEN-LAST:event_iniciarSesionBtnActionPerformed

    private void solicitarVacacionesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitarVacacionesBtnMouseClicked
        controlador.noImplementado();
    }//GEN-LAST:event_solicitarVacacionesBtnMouseClicked

    private void registrarNuevoEmpleadoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarNuevoEmpleadoBtnMouseClicked
        controlador.procesarNuevoEmpleado();
    }//GEN-LAST:event_registrarNuevoEmpleadoBtnMouseClicked

    private void erteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_erteBtnMouseClicked
        controlador.noImplementado();
    }//GEN-LAST:event_erteBtnMouseClicked

    private void recepcionPedidoTiendaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recepcionPedidoTiendaBtnMouseClicked
        controlador.procesarPedidoTienda();
    }//GEN-LAST:event_recepcionPedidoTiendaBtnMouseClicked

    private void realizarPedidoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarPedidoBtnMouseClicked
        controlador.noImplementado();
    }//GEN-LAST:event_realizarPedidoBtnMouseClicked

    private void disponibilidadProductoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disponibilidadProductoBtnMouseClicked
        controlador.procesarDisponibilidadProducto();
    }//GEN-LAST:event_disponibilidadProductoBtnMouseClicked

    private void enviarProductoAlmacenBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarProductoAlmacenBtnMouseClicked
        controlador.noImplementado();
    }//GEN-LAST:event_enviarProductoAlmacenBtnMouseClicked

    /**
     * Obtiene el dni introducido por el usuario
     *
     * @return dni del usuario
     */
    public String getDni() {
        return nombreUsuarioTextField.getText();
    }

    /**
     * Obtiene la contraseña introducida por el usuario
     *
     * @return contraseña del usuario
     */
    public char[] getContrasena() {
        return contrasenaField.getPassword();
    }

    /**
     * Muestra mensaje de error
     *
     * @param mensaje
     */
    public void setMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Si el usuario que ha iniciado sesion es del tipo 2, se muestran las
     * opciones que tiene disponibles.
     */
    public void rolDos() {
        registrarNuevoEmpleadoBtn.setEnabled(true);
        erteBtn.setEnabled(true);
    }

    /**
     * Si el usuario que ha iniciado sesion es del tipo 3, se muestran las
     * opciones que tiene disponibles.
     */
    public void rolTres() {
        disponibilidadProductoBtn.setEnabled(true);
        enviarProductoAlmacenBtn.setEnabled(true);
    }

    /**
     * Si el usuario que ha iniciado sesion es del tipo 5, se muestran las
     * opciones que tiene disponibles.
     */
    public void rolCinco() {
        recepcionPedidoTiendaBtn.setEnabled(true);
        realizarPedidoBtn.setEnabled(true);
    }

    /**
     * Si el usuario que ha iniciado sesion es del tipo 5, se muestran las
     * opciones que tiene disponibles.
     */
    public void setOpcionPanelVisible() {
        opcionesPanel.setVisible(true);
        iniciarSesionPanel.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contrasenaField;
    private javax.swing.JLabel contrasenaLabel;
    private javax.swing.JButton disponibilidadProductoBtn;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JLabel empresaLabel;
    private javax.swing.JButton enviarProductoAlmacenBtn;
    private javax.swing.JButton erteBtn;
    private javax.swing.JToggleButton iniciarSesionBtn;
    private javax.swing.JPanel iniciarSesionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombreUsuarioTextField;
    private javax.swing.JPanel opcionesPanel;
    private javax.swing.JButton realizarPedidoBtn;
    private javax.swing.JButton recepcionPedidoTiendaBtn;
    private javax.swing.JButton registrarNuevoEmpleadoBtn;
    private javax.swing.JButton solicitarVacacionesBtn;
    // End of variables declaration//GEN-END:variables
}
