package es.uva.bluemanzana.interfaz.paresvistacontrol;

import es.uva.bluemanzana.interfaz.paresvistacontrol.RegistrarseVistaCtrl;
import es.uva.bluemanzana.app.BlueManzana;
import es.uva.bluemanzana.negocio.modelo.Usuario;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Clase que implementa la interfaz que se muestra a un usuario cuando realiza
 * el caso de uso de Registrar un nuevo emplado.
 *
 * @author sergsan
 * @author juatorr
 * @author pabvare
 */
public class RegistrarseVista extends javax.swing.JFrame {

    private RegistrarseVistaCtrl controladorReg;
    private Usuario usuario;

    /**
     * Constructor de la interfaz, utiliza el usuario con el que se ha iniciado
     * sesión en el sistema.
     *
     * @param usuario
     */
    public RegistrarseVista(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        controladorReg = new RegistrarseVistaCtrl(this);
        panelTrasComprobar.setVisible(false);
        labelErrorDNI.setVisible(false);
        labelErrorGlobal.setVisible(false);
        botonRegistrar.setVisible(false);
        panelDireccion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        panelTrasComprobar = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelIBAN = new javax.swing.JLabel();
        labelNumSecSoc = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        textFieldApellidos = new javax.swing.JTextField();
        textFieldTelefono = new javax.swing.JTextField();
        textFieldEmail = new javax.swing.JTextField();
        textFieldIBAN = new javax.swing.JTextField();
        textFieldNumSegSoc = new javax.swing.JTextField();
        panelRolDestino = new javax.swing.JPanel();
        labelRol = new javax.swing.JLabel();
        labelDestino = new javax.swing.JLabel();
        textFieldRol = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDestinos = new javax.swing.JList<>();
        botonDireccion = new javax.swing.JButton();
        panelDireccion = new javax.swing.JPanel();
        labelCalle = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        labelOtros = new javax.swing.JLabel();
        labelCodPos = new javax.swing.JLabel();
        labelLocalidad = new javax.swing.JLabel();
        labelProvincia = new javax.swing.JLabel();
        textFieldCalle = new javax.swing.JTextField();
        textFieldNumero = new javax.swing.JTextField();
        textFieldOtros = new javax.swing.JTextField();
        textFieldCodPos = new javax.swing.JTextField();
        textFieldLocalidad = new javax.swing.JTextField();
        textFieldProvincia = new javax.swing.JTextField();
        botonGuardarDireccion = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        botonComprobar = new javax.swing.JButton();
        labelNIF = new javax.swing.JLabel();
        textFieldNIF = new javax.swing.JTextField();
        labelErrorDNI = new javax.swing.JLabel();
        labelErrorGlobal = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelTitulo.setText("Registro nuevo empleado");

        labelNombre.setText("Nombre:");

        labelApellidos.setText("Apellidos:");

        labelTelefono.setText("Telefono:");

        labelEmail.setText("Email:");

        labelDireccion.setText("Direccion:");

        labelIBAN.setText("IBAN:");

        labelNumSecSoc.setText("Numero Seg. Social:");

        textFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreActionPerformed(evt);
            }
        });

        textFieldApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldApellidosActionPerformed(evt);
            }
        });

        textFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTelefonoActionPerformed(evt);
            }
        });

        textFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmailActionPerformed(evt);
            }
        });

        labelRol.setText("Rol:");

        labelDestino.setText("Destino:");

        listaDestinos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaDestinos);

        javax.swing.GroupLayout panelRolDestinoLayout = new javax.swing.GroupLayout(panelRolDestino);
        panelRolDestino.setLayout(panelRolDestinoLayout);
        panelRolDestinoLayout.setHorizontalGroup(
            panelRolDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRolDestinoLayout.createSequentialGroup()
                .addGroup(panelRolDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRol)
                    .addComponent(labelDestino))
                .addGap(93, 93, 93)
                .addGroup(panelRolDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldRol, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRolDestinoLayout.setVerticalGroup(
            panelRolDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRolDestinoLayout.createSequentialGroup()
                .addGroup(panelRolDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRol)
                    .addComponent(textFieldRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRolDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRolDestinoLayout.createSequentialGroup()
                        .addComponent(labelDestino)
                        .addGap(0, 81, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        botonDireccion.setText("+ Añadir nueva direccion");
        botonDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDireccionActionPerformed(evt);
            }
        });

        labelCalle.setText("Calle:");

        labelNumero.setText("Numero:");

        labelOtros.setText("Otros:");

        labelCodPos.setText("C.P.");

        labelLocalidad.setText("Localidad:");

        labelProvincia.setText("Provincia:");

        textFieldLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLocalidadActionPerformed(evt);
            }
        });

        textFieldProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldProvinciaActionPerformed(evt);
            }
        });

        botonGuardarDireccion.setText("Guardar");
        botonGuardarDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarDireccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDireccionLayout = new javax.swing.GroupLayout(panelDireccion);
        panelDireccion.setLayout(panelDireccionLayout);
        panelDireccionLayout.setHorizontalGroup(
            panelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDireccionLayout.createSequentialGroup()
                .addGroup(panelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDireccionLayout.createSequentialGroup()
                        .addComponent(labelCalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDireccionLayout.createSequentialGroup()
                        .addComponent(labelNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldNumero))
                    .addGroup(panelDireccionLayout.createSequentialGroup()
                        .addComponent(labelOtros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldOtros))
                    .addGroup(panelDireccionLayout.createSequentialGroup()
                        .addComponent(labelCodPos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldCodPos))
                    .addGroup(panelDireccionLayout.createSequentialGroup()
                        .addComponent(labelLocalidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldLocalidad))
                    .addGroup(panelDireccionLayout.createSequentialGroup()
                        .addComponent(labelProvincia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldProvincia)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDireccionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardarDireccion)
                .addContainerGap())
        );
        panelDireccionLayout.setVerticalGroup(
            panelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDireccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCalle)
                    .addComponent(textFieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumero)
                    .addComponent(textFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOtros)
                    .addComponent(textFieldOtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodPos)
                    .addComponent(textFieldCodPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLocalidad)
                    .addComponent(textFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProvincia)
                    .addComponent(textFieldProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonGuardarDireccion)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTrasComprobarLayout = new javax.swing.GroupLayout(panelTrasComprobar);
        panelTrasComprobar.setLayout(panelTrasComprobarLayout);
        panelTrasComprobarLayout.setHorizontalGroup(
            panelTrasComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrasComprobarLayout.createSequentialGroup()
                .addGroup(panelTrasComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTrasComprobarLayout.createSequentialGroup()
                        .addGroup(panelTrasComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(labelDireccion)
                            .addComponent(labelNumSecSoc)
                            .addComponent(labelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(panelTrasComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldApellidos)
                            .addComponent(textFieldNombre)
                            .addComponent(textFieldTelefono)
                            .addComponent(textFieldEmail)
                            .addComponent(textFieldIBAN)
                            .addComponent(textFieldNumSegSoc)
                            .addComponent(botonDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelRolDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTrasComprobarLayout.setVerticalGroup(
            panelTrasComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrasComprobarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTrasComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTrasComprobarLayout.createSequentialGroup()
                        .addGroup(panelTrasComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(panelTrasComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(panelTrasComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(panelTrasComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(panelTrasComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonDireccion))
                        .addGap(3, 3, 3)
                        .addGroup(panelTrasComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(panelTrasComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNumSecSoc, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNumSegSoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRolDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        botonComprobar.setText("Comprobar");
        botonComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprobarActionPerformed(evt);
            }
        });

        labelNIF.setText("NIF:");

        textFieldNIF.setToolTipText("");
        textFieldNIF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textFieldNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNIFActionPerformed(evt);
            }
        });
        textFieldNIF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldNIFKeyTyped(evt);
            }
        });

        labelErrorDNI.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorDNI.setText("El nif introducido no es correcto. Intentalo de nuevo.");

        labelErrorGlobal.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorGlobal.setText("Error general");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTrasComprobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(labelErrorGlobal)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelErrorDNI)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonComprobar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonRegistrar)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldNIF)
                                .addGap(119, 119, 119))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addGap(137, 137, 137))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNIF)
                    .addComponent(textFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(labelErrorDNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTrasComprobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrar)
                    .addComponent(botonComprobar)
                    .addComponent(botonCancelar)
                    .addComponent(labelErrorGlobal))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNIFActionPerformed

    private void textFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmailActionPerformed

    private void textFieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldApellidosActionPerformed

    private void textFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTelefonoActionPerformed

    private void textFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreActionPerformed

    private void botonComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprobarActionPerformed
        controladorReg.procesaBotonComprobar();
    }//GEN-LAST:event_botonComprobarActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        controladorReg.procesaBotonRegistrar();
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void textFieldNIFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldNIFKeyTyped
        if (textFieldNIF.getText().length() == 9) {
            evt.consume();
        }
    }//GEN-LAST:event_textFieldNIFKeyTyped

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        controladorReg.procesaBotonCancelar();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void textFieldLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLocalidadActionPerformed

    private void textFieldProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldProvinciaActionPerformed

    private void botonDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDireccionActionPerformed
        controladorReg.procesaBotonDireccion();
    }//GEN-LAST:event_botonDireccionActionPerformed

    private void botonGuardarDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarDireccionActionPerformed
        controladorReg.procesaBotonGuardar();
    }//GEN-LAST:event_botonGuardarDireccionActionPerformed

    /**
     * Funcion encargada de mostrar el panel de introduccion de datos personales
     * tras comprobar el nif introducido.
     */
    public void muestraPanelComprueba() {
        panelTrasComprobar.setVisible(true);
        textFieldNIF.setEnabled(false);
        labelErrorDNI.setVisible(false);
        panelRolDestino.setVisible(false);
    }

    /**
     * Funcion encangarda de mostrar el panel para introducir una nueva
     * direccion.
     */
    public void muestraPanelDireccion() {
        panelDireccion.setVisible(true);
    }

    /**
     * Funcion encargada de ocultar el panel de introducir una nueva direccion.
     */
    public void ocultaPanelDireccion() {
        panelDireccion.setVisible(false);
        botonDireccion.setText("Direccion guardada");
        botonDireccion.setEnabled(false);

    }

    /**
     * Funcion encargada de mostrar el panel para introducir rol y destino.
     */
    public void muestraPanelRolDest() {
        labelErrorGlobal.setVisible(false);
        panelRolDestino.setVisible(true);
        botonComprobar.setVisible(false);
        botonRegistrar.setVisible(true);
        textFieldNombre.setEnabled(false);
        textFieldApellidos.setEnabled(false);
        textFieldTelefono.setEnabled(false);
        textFieldEmail.setEnabled(false);
        textFieldIBAN.setEnabled(false);
        textFieldNumSegSoc.setEnabled(false);

    }

    /**
     * Funcion encargada de mostrar un messageDialog tras un registro correcto.
     *
     * @param pass Contrasena temporal asignada al empleado.
     */
    public void registroCorrecto(String pass) {
        //Pruebas, aqui habria que cambiar de vista
        JFrame frameAviso = new JFrame();
        JOptionPane.showMessageDialog(frameAviso, "Se ha asignado la siguiente contraseña temporal: " + pass + ".\nEsta debe ser modificada inmediatamente a traves del sistema.");
        labelErrorGlobal.setVisible(false);
        panelTrasComprobar.setVisible(false);
        labelNIF.setVisible(false);
        textFieldNIF.setVisible(false);
        labelTitulo.setVisible(false);
        botonRegistrar.setVisible(false);
        panelRolDestino.setVisible(false);
        botonCancelar.setText("Ir a inicio de sesion");
    }

    /**
     * Funcion encargada de mostrar error tras introducir un dni erroneo o ya en
     * la base de datos.
     *
     * @param caso Tipo de error a mostrar.
     */
    public void muestraErrorDNI(int caso) {
        switch (caso) {
            case 1:
                labelErrorDNI.setVisible(true);
                labelErrorDNI.setText("El dni introducido es incorrecto.");
                break;
            case 2:
                labelErrorDNI.setVisible(true);
                labelErrorDNI.setText("El dni introducido ya esta registrado.");
                break;
        }

    }

    /**
     * Funcion encargada de mostrar un error general que se modificara el texto
     * en funcion del parametro.
     *
     * @param error Tipo de error a mostrar.
     */
    public void muestraError(String error) {
        labelErrorGlobal.setVisible(true);
        switch (error.toLowerCase()) {
            case "nombre":
                labelErrorGlobal.setText("Formato Nombre Incorrecto");
                break;

            case "apellido":
                labelErrorGlobal.setText("Formato Apellidos Incorrecto");
                break;

            case "telefono":
                labelErrorGlobal.setText("Formato Telefono Incorrecto");
                break;

            case "email":
                labelErrorGlobal.setText("Formato Email Incorrecto");
                break;

            case "iban":
                labelErrorGlobal.setText("Formato IBAN Incorrecto");
                break;

            case "ss":
                labelErrorGlobal.setText("Formato Numero Seg. Social Incorrecto");
                break;

            case "roles":
                labelErrorGlobal.setText("Combinacion Rol-Destino Incompatible");
                break;

            case "botdireccion":
                labelErrorGlobal.setText("No se ha añadido ninguna direccion");
                break;

            case "destino":
                labelErrorGlobal.setText("No se ha seleccionado ningun destino");
                break;
        }
    }

    /**
     * Consulta para obtener si el boton de nueva direccion esta activado.
     *
     * @return true/false en funcion del estado del boton.
     */
    public boolean isEnabledBotonDireccion() {
        return botonDireccion.isEnabled();
    }

    /**
     * Consulta que devuelve el dni introducido en el cuadro de texto
     * correspondiente.
     *
     * @return dni
     */
    public String getNIF() {
        return textFieldNIF.getText();
    }

    /**
     * Consulta que devuelve el nombre introducido en el cuadro de texto
     * correspondiente.
     *
     * @return nombre
     */
    public String getNombre() {
        return textFieldNombre.getText();
    }

    /**
     * Consulta que devuelve los apellidos introducidos en el cuadro de texto
     * correspondiente.
     *
     * @return apellidos
     */
    public String getApellidos() {
        return textFieldApellidos.getText();
    }

    /**
     * Consulta que devuelve el telefono introducido en el cuadro de texto
     * correspondiente.
     *
     * @return telefono
     */
    public String getTelefono() {
        return textFieldTelefono.getText();
    }

    /**
     * Consulta que devuelve el email introducido en el cuadro de texto
     * correspondiente.
     *
     * @return email
     */
    public String getEmail() {
        return textFieldEmail.getText();
    }

    /**
     * Consulta que devuelve el numero de seguridad social introducido en el
     * cuadro de texto correspondiente.
     *
     * @return numero de seguridad social
     */
    public String getNumSegSoc() {
        return textFieldNumSegSoc.getText();
    }

    /**
     * Consulta que devuelve el iban introducido en el cuadro de texto
     * correspondiente.
     *
     * @return iban
     */
    public String getIban() {
        return textFieldIBAN.getText();
    }

    /**
     * Consulta que devuelve el rol introducido en el cuadro de texto
     * correspondiente.
     *
     * @return
     */
    public String getRol() {
        return textFieldRol.getText();
    }

    /**
     * Asigna la lista de destinos en el jList que puede tener el nuevo empleado
     *
     * @param destinos lista de destinos
     */
    public void setListaDestinos(String[] destinos) {
        listaDestinos.setListData(destinos);
    }

    /**
     * Consulta que obtiene el elemento seleccionado de los destinos.
     *
     * @return el destino selecionada por el usuario.
     */
    public String getDestinoSelected() {
        return listaDestinos.getSelectedValue();
    }

    /**
     * Consulta que devuelve el indice del elemento seleccionado de los
     * destinos.
     *
     * @return indice del destino seleccionado.
     */
    public int getDestinoSelectedIndex() {
        return listaDestinos.getSelectedIndex();
    }

    /**
     * Consulta que devuelve la calle introducido en el cuadro de texto
     * correspondiente.
     *
     * @return calle introducida
     */
    public String getCalle() {
        return textFieldCalle.getText();
    }

    /**
     * Consulta que devuelve el numero introducido en el cuadro de texto
     * correspondiente.
     *
     * @return numero introducido
     */
    public int getNumeroDir() {
        return Integer.parseInt(textFieldNumero.getText());
    }

    /**
     * Consulta que devuelve el apartado otros introducido en el cuadro de texto
     * correspondiente.
     *
     * @return otros
     */
    public String getOtros() {
        return textFieldOtros.getText();
    }

    /**
     * Consulta que devuelve el codigo postal introducido en el cuadro de texto
     * correspondiente.
     *
     * @return codigo postal introducido.
     */
    public int getCodPos() {
        return Integer.parseInt(textFieldCodPos.getText());
    }

    /**
     * Consulta que devuelve la localidad introducida en el cuadro de texto
     * correspondiente.
     *
     * @return localidad introducida
     */
    public String getLocalidad() {
        return textFieldLocalidad.getText();
    }

    /**
     * Consulta que devuelve la provincia introducida en el cuadro de texto
     * correspondiente.
     *
     * @return provincia introducida.
     */
    public String getProvincia() {
        return textFieldProvincia.getText();
    }

    /**
     * Funcion encargada de llamar a la maquina de estados para cambiar a vista
     * identificarse.
     */
    public void cambiarAVistaIdentificarse() {
        BlueManzana.getStateMachine().abrirVistaIdentificarse(usuario);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonComprobar;
    private javax.swing.JButton botonDireccion;
    private javax.swing.JButton botonGuardarDireccion;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelCalle;
    private javax.swing.JLabel labelCodPos;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelErrorDNI;
    private javax.swing.JLabel labelErrorGlobal;
    private javax.swing.JLabel labelIBAN;
    private javax.swing.JLabel labelLocalidad;
    private javax.swing.JLabel labelNIF;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumSecSoc;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelOtros;
    private javax.swing.JLabel labelProvincia;
    private javax.swing.JLabel labelRol;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JList<String> listaDestinos;
    private javax.swing.JPanel panelDireccion;
    private javax.swing.JPanel panelRolDestino;
    private javax.swing.JPanel panelTrasComprobar;
    private static javax.swing.JTextField textFieldApellidos;
    private javax.swing.JTextField textFieldCalle;
    private javax.swing.JTextField textFieldCodPos;
    private static javax.swing.JTextField textFieldEmail;
    private static javax.swing.JTextField textFieldIBAN;
    private javax.swing.JTextField textFieldLocalidad;
    private static javax.swing.JTextField textFieldNIF;
    private static javax.swing.JTextField textFieldNombre;
    private static javax.swing.JTextField textFieldNumSegSoc;
    private javax.swing.JTextField textFieldNumero;
    private javax.swing.JTextField textFieldOtros;
    private javax.swing.JTextField textFieldProvincia;
    private javax.swing.JTextField textFieldRol;
    private static javax.swing.JTextField textFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
